// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SigData } from "./SigData";
import type { SpartanMerkleProof } from "./SpartanMerkleProof";

export interface AddrMembershipV1Inputs {
  sigData: SigData;
  merkleProof: SpartanMerkleProof;
}
