// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleSigPosRangeV1Data } from "./MerkleSigPosRangeV1Data";
import type { SimpleHashV1Data } from "./SimpleHashV1Data";

export type CircuitTypeData = SimpleHashV1Data | MerkleSigPosRangeV1Data;
