// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CircuitTypeId = "simple_hash_v1" | "addr_membership_v1" | "merkle_sig_pos_range_v1";
