// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleSigPosRangeV1CircuitPubInputs } from "./MerkleSigPosRangeV1CircuitPubInputs";

export interface MerkleSigPosRangeV1PublicInputs {
  circuitPubInput: MerkleSigPosRangeV1CircuitPubInputs;
  nonceRaw: string;
  proofPubKey: string;
  assetSizeLabel: string;
  proofIdentityInput: string;
}
