// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeData } from "./RangeData";

export interface MerkleSigPosRangeV1Data {
  prfs_set_id: string;
  range_data: RangeData;
}
