// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MerkleSigPosExactV1CircuitPubInputs = {
  merkleRoot: bigint;
  nonceInt: bigint;
  proofPubKeyInt: bigint;
  serialNo: bigint;
  valueInt: bigint;
};
