// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleSigPosExactV1CircuitPubInputs } from "./MerkleSigPosExactV1CircuitPubInputs";

export type MerkleSigPosExactV1PublicInputs = {
  circuitPubInput: MerkleSigPosExactV1CircuitPubInputs;
  nonceRaw: string;
  proofPubKey: string;
  valueRaw: string;
  proofIdentityInput: string;
};
