// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RangeOption {
  label: string;
  lower_bound: bigint;
  upper_bound: bigint;
}
