// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashData } from "./HashData";

export type SimpleHashV1Inputs = { hashData: HashData; proofPubKey: string };
