[workspace]
members = [
  # externals
  "externals/secq256k1",
  "externals/poseidon",
  "externals/Spartan-secq",
  "externals/circuit_reader",

  # prfs
  "source/prfs_db_interface",
  "source/prfs_tree_maker",
  "source/prfs_api_server",
  "source/prfs_asset_server",
  "source/prfs_crypto",
  "source/prfs_entities",

  # prfs cicuits
  "source/prfs_circuit_circom",
  "source/prfs_circom_analyzer",

  # prfs driver
  "source/prfs_driver_spartan_wasm",

  # internals
  "internals/ci",
]
