[workspace]
members = [
  # externals
  "externals/spartan_wasm",
  "externals/secq256k1",
  "externals/poseidon",
  "externals/Spartan-secq",
  "externals/circuit_reader",

  # prfs
  "source/prfs_wasm",
  "source/prfs_circuit_server",

  # internals
  "internals/ci",
]
