[workspace]
members = [
    "packages/spartan_wasm",
    "packages/secq256k1",
    "packages/poseidon",
    "packages/Spartan-secq",
    "packages/circuit_reader",

    # prfs
    "source/prfs_wasm",
    "source/prfs_circuit_server",
    "internals/ci",
]
