packages:
  # Externals

  # Prfs
  - "source/prfs_circuit_artifact_uri_resolver"
  - "source/prfs_docs_website"
  - "source/prfs_driver_o1js"
  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_interface"
  - "source/prfs_circuit_interface"
  - "source/prfs_circuits_circom"
  - "source/prfs_crypto_js"
  - "source/prfs_crypto_deps_js"
  - "source/prfs_entities"
  - "source/prfs_i18n"
  - "source/prfs_env"
  - "source/prfs_react_lib"
  - "source/prfs_id_api_error_codes"
  - "source/prfs_id_sdk_web"
  - "source/prfs_id_session_api_error_codes"
  - "source/prfs_proof_gen_js"
  - "source/prfs_tree_api_error_codes"
  - "source/prfs_ts_utils"
  - "source/prfs_api_js"
  - "source/prfs_api_lib_js"
  - "source/prfs_api_error_codes"
  - "source/prfs_api_server"
  - "source/prfs_atst_api_error_codes"
  - "source/prfs_snap"
  - "source/prfs_proof_webapp"
  - "source/prfs_console_webapp"
  - "source/prfs_poll_webapp"
  - "source/prfs_id_webapp"
  - "source/prfs_circuits_o1js"

  # Shy
  - "source/shy_webapp"
  - "source/shy_api_error_codes"
  - "source/shy_api_js"
  - "source/shy_entities"
  - "source/shy_api_server"
  - "source/shy_docs_website"
