packages:
  - "externals/incremental-merkle-tree"

  - "source/e2e_test_web"

  - "source/prfs_circuit_circom"

  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_interface"

  - "source/prfs_crypto_js"
  - "source/prfs_api_js"
  - "source/prfs_entities"

  - "source/prfs_sdk_web"
  - "source/prfs_sdk_web_module"
  - "source/prfs_react_components"

  - "source/webapp_console"
  - "source/webapp_proof"
  - "source/webapp_poll"
  - "source/webapp_vacade"
