packages:
  - "externals/incremental-merkle-tree"
  - "source/e2e_test_web"
  - "source/prfs_crypto_js"
  - "source/prfs_driver_spartan_js"
  - "source/prfs_driver_type"
  - "source/prfs_driver_interface"
  - "source/prfs_circuit_circom"
  - "source/prfs_sdk_web"
  - "source/prfs_web"
