import './globals.css'
import { Inter } from 'next/font/google'

import { I18nContext } from '@/contexts';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <I18nContext.Provider value={{}}>
        <body className={inter.className}>{children}</body>
      </I18nContext.Provider>
    </html>
  )
}
