export interface Envs {
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_ID_SESSION_SOCKET_ENDPOINT: string;
}

export const envs: Envs = {
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT,
  NEXT_PUBLIC_PRFS_ID_SESSION_SOCKET_ENDPOINT:
    process.env.NEXT_PUBLIC_PRFS_ID_SESSION_SOCKET_ENDPOINT,
};
