// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsEnv {
  taigalabs_website: string;
  prfs_code_repository: string;
  prfs_id_webapp: string;
  prfs_console_webapp: string;
  prfs_proof_webapp: string;
  prfs_poll_webapp: string;
  prfs_docs_website: string;
  prfs_api_server: string;
  prfs_asset_server: string;
  prfs_id_session_server_socket: string;
  shy_webapp: string;
  shy_docs_website: string;
}
