export interface Envs {
  NEXT_PUBLIC_IS_TEASER: string;
  NEXT_PUBLIC_UPDATE_TIMESTAMP: string;
  NEXT_PUBLIC_CODE_REPOSITORY_URL: string;
  NEXT_PUBLIC_TAIGALABS_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_ID_WEBAPP_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_TWITTER_OAUTH_REDIRECT_URL: string;
  NEXT_PUBLIC_PRFS_AUTH_OP_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT: string;
  NEXT_PUBLIC_ZAUTH_VERSION: string;
  NEXT_PUBLIC_DOCS_WEBSITE_ENDPOINT: string;
}

export const envs: Envs = {
  NEXT_PUBLIC_IS_TEASER: process.env.NEXT_PUBLIC_IS_TEASER,
  NEXT_PUBLIC_UPDATE_TIMESTAMP: process.env.NEXT_PUBLIC_UPDATE_TIMESTAMP,
  NEXT_PUBLIC_CODE_REPOSITORY_URL: process.env.NEXT_PUBLIC_CODE_REPOSITORY_URL,
  NEXT_PUBLIC_TAIGALABS_ENDPOINT: process.env.NEXT_PUBLIC_TAIGALABS_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT,
  NEXT_PUBLIC_PRFS_ID_WEBAPP_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_ID_WEBAPP_ENDPOINT,
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT,
  NEXT_PUBLIC_TWITTER_OAUTH_REDIRECT_URL: process.env.NEXT_PUBLIC_TWITTER_OAUTH_REDIRECT_URL,
  NEXT_PUBLIC_PRFS_AUTH_OP_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_AUTH_OP_SERVER_ENDPOINT,
  NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT,
  NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT,
  NEXT_PUBLIC_ZAUTH_VERSION: process.env.NEXT_PUBLIC_ZAUTH_VERSION,
  NEXT_PUBLIC_DOCS_WEBSITE_ENDPOINT: process.env.NEXT_PUBLIC_DOCS_WEBSITE_ENDPOINT,
};
