export const paths = {
  __: "/",
  create: "/create",
  // auth: "/auth",
  attestations: "/attestations",
  attestations__create: "/attestations/create",
  attestations__twitter: "/attestations/twitter",
  proofs: "/proofs",
  updates: "/updates",
  privacy: "/privacy",
  // id: "/id",
  // id__create_id: "/id/create_id",
  // id__app_signin: "/id/app_signin",
  accounts: "/accounts",
};
