export const paths = {
  __: "/",
  create: "/create",
  sets: "/sets",
  sets__create: "/sets/create",
  sets__crypto_holders: "/sets/crypto_holders",
  attestations: "/attestations",
  attestations__create__twitter: "/attestations/create/twitter",
  attestations__create__crypto_size: "/attestations/create/crypto_size",
  attestations__twitter: "/attestations/twitter",
  attestations__crypto_size: "/attestations/crypto_size",
  proofs: "/proofs",
  updates: "/updates",
  privacy: "/privacy",
  accounts: "/accounts",
};
