// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SpartanCircomDriverProperties { wtns_gen_url: string, circuit_url: string, instance_path: string, }