[package]
name = "spartan_wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "spartan_wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spartan = { path = "../Spartan-secq" }
wasm-bindgen = { version = "0.2.81", features = ["serde-serialize"]}
console_error_panic_hook = "0.1.7"
merlin = "3.0.0"
web-sys = { version = "0.3.60", features = ["console"] }
serde_json = "1.0.89"
num-bigint = "0.4.3"
serde = "1.0.151"
byteorder = "1.4.3"
ff = "0.12.0"
secq256k1 = { path = "../secq256k1" }
serde-wasm-bindgen = "0.4.5"
bincode = "1.3.3"
# Not directly using getrandom in this crate, 
# but some dependencies require getrandom 
# and the "js" features needs to be enabled for wasm compatibility
getrandom = { version = "0.2.8", features = ["js"] }
poseidon = { path = "../poseidon" }
itertools = "0.9.0"
group = "0.12.0"

