// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateShyCommentAction = { topic_id: string; comment_id: string; content: string };
