// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateShyCommentRequest = {
  topic_id: string;
  channel_id: string;
  comment_id: string;
  content: string;
  author_public_key: string;
  author_sig: string;
  sub_channel_id: string;
};
