// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateShyTopicAction {
  topic_id: string;
  channel_id: string;
  content: string;
}
