// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofBlob } from "./ProofBlob";

export type CreateShyTopicRequest = {
  title: string;
  topic_id: string;
  content: string;
  channel_id: string;
  serial_no: string;
  sub_channel_id: string;
  proofs: Array<ProofBlob>;
};
