// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofBlob } from "./ProofBlob";

export type CreateShyCommentRequest = {
  topic_id: string;
  channel_id: string;
  shy_proof_id: string;
  comment_id: string;
  content: string;
  author_public_key: string;
  author_sig: string;
  author_sig_msg: Array<number>;
  other_proofs: Array<ProofBlob>;
};
