// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnterShyChannelToken = { shy_proof_id: string; sig: string; sig_msg: Array<number> };
