// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyTopicSyn1 } from "./ShyTopicSyn1";

export type GetShyTopicResponse = { shy_topic: ShyTopicSyn1 };
