// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyPost } from "./ShyPost";

export interface GetShyPostResponse {
  shy_post: DateTimed<ShyPost>;
}
