// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyPost } from "./ShyPost";

export type GetShyPostsOfTopicResponse = {
  rows: Array<DateTimed<ShyPost>>;
  next_offset: number | null;
};
