// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyCommentWithProofs } from "./ShyCommentWithProofs";

export type GetShyCommentsOfTopicResponse = {
  shy_comments_with_proofs: Array<ShyCommentWithProofs>;
  next_offset: number | null;
};
