// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyCommentWithProofs } from "./ShyCommentWithProofs";

export type GetShyCommentsOfTopicResponse = {
  rows: Array<DateTimed<ShyCommentWithProofs>>;
  next_offset: number | null;
};
