// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyTopicWithProofs } from "./ShyTopicWithProofs";

export type GetShyTopicResponse = { shy_topic_with_proofs: ShyTopicWithProofs };
