// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyTopicSyn1 } from "./ShyTopicSyn1";

export type GetShyTopicsResponse = {
  shy_topic_syn1s: Array<ShyTopicSyn1>;
  next_offset: number | null;
};
