// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyProof } from "./ShyProof";

export type GetShyProofResponse = { shy_proof: ShyProof };
