// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyTopicSyn1 } from "./ShyTopicSyn1";

export interface GetShyTopicResponse {
  shy_topic_syn1: DateTimed<ShyTopicSyn1>;
}
