// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyTopicProof } from "./ShyTopicProof";

export interface GetShyTopicProofResponse {
  shy_topic_proof: ShyTopicProof;
}
