// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProofIdentity = {
  shy_proof_id: string;
  proof_type_id: string;
  proof_identity_input: string;
  proof_public_key: string;
  proof_sig: string;
};
