// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProofBlob = {
  shy_proof_id: string;
  proof_identity_input: string;
  proof: Array<number>;
  public_inputs: string;
  serial_no: string;
  author_public_key: string;
  author_sig: string;
  author_sig_msg: Array<number>;
  proof_type_id: string;
  proof_idx: number;
  is_required: boolean;
};
