// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyAccount {
  account_id: string;
  public_key: string;
  avatar_color: string;
}
