// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateShyPostRequest } from "./CreateShyPostRequest";
import type { CreateShyTopicRequest } from "./CreateShyTopicRequest";
import type { GetShyChannelsRequest } from "./GetShyChannelsRequest";
import type { GetShyPostsOfTopicRequest } from "./GetShyPostsOfTopicRequest";
import type { GetShyTopicProofRequest } from "./GetShyTopicProofRequest";
import type { GetShyTopicRequest } from "./GetShyTopicRequest";
import type { GetShyTopicsRequest } from "./GetShyTopicsRequest";

export type ShyApiRequest =
  | ({ type: "create_shy_topic" } & CreateShyTopicRequest)
  | ({ type: "create_shy_post" } & CreateShyPostRequest)
  | ({ type: "get_shy_channels" } & GetShyChannelsRequest)
  | ({ type: "get_shy_topics" } & GetShyTopicsRequest)
  | ({ type: "get_shy_topic" } & GetShyTopicRequest)
  | ({ type: "get_shy_topic_proof" } & GetShyTopicProofRequest)
  | ({ type: "get_shy_posts_of_topic" } & GetShyPostsOfTopicRequest)
  | ({ type: "get_shy_channel" } & GetShyChannelsRequest);
