// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateShyCommentRequest } from "./CreateShyCommentRequest";
import type { CreateShyCommentWithProofsRequest } from "./CreateShyCommentWithProofsRequest";
import type { CreateShyTopicRequest } from "./CreateShyTopicRequest";
import type { GetShyChannelsRequest } from "./GetShyChannelsRequest";
import type { GetShyCommentsOfTopicRequest } from "./GetShyCommentsOfTopicRequest";
import type { GetShyProofsRequest } from "./GetShyProofsRequest";
import type { GetShyTopicRequest } from "./GetShyTopicRequest";
import type { GetShyTopicsRequest } from "./GetShyTopicsRequest";
import type { JoinShyChannelRequest } from "./JoinShyChannelRequest";
import type { SignInShyAccountRequest } from "./SignInShyAccountRequest";
import type { SignUpShyAccountRequest } from "./SignUpShyAccountRequest";

export type ShyApiRequest =
  | ({ type: "create_shy_topic" } & CreateShyTopicRequest)
  | ({ type: "create_shy_comment" } & CreateShyCommentRequest)
  | ({ type: "create_shy_comment_with_proofs" } & CreateShyCommentWithProofsRequest)
  | ({ type: "sign_up_shy_account" } & SignUpShyAccountRequest)
  | ({ type: "sign_in_shy_account" } & SignInShyAccountRequest)
  | ({ type: "get_shy_channels" } & GetShyChannelsRequest)
  | ({ type: "get_shy_channel" } & GetShyChannelsRequest)
  | ({ type: "get_shy_topics" } & GetShyTopicsRequest)
  | ({ type: "get_shy_topic" } & GetShyTopicRequest)
  | ({ type: "get_shy_proofs" } & GetShyProofsRequest)
  | ({ type: "get_shy_comments_of_topic" } & GetShyCommentsOfTopicRequest)
  | ({ type: "join_shy_channel" } & JoinShyChannelRequest);
