// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShyChannelMember = {
  serial_no: string;
  channel_id: string;
  shy_proof_id: string;
  public_key: string;
};
