// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateShyCommentAction } from "./CreateShyCommentAction";

export type ShyCommentProofAction = { type: "create_shy_comment" } & CreateShyCommentAction;
