// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyComment } from "./ShyComment";
import type { ShyProofWithProofType } from "./ShyProofWithProofType";

export type ShyCommentWithProofs = {
  shy_comment: DateTimed<ShyComment>;
  shy_proofs: Array<ShyProofWithProofType>;
};
