// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locale } from "./Locale";
import type { ShyChannelStatus } from "./ShyChannelStatus";
import type { ShyChannelType } from "./ShyChannelType";

export type ShyChannel = {
  channel_id: string;
  label: string;
  locale: Locale;
  desc: string;
  proof_type_ids: string[];
  assoc_proof_type_ids: Record<string, string>[];
  status: ShyChannelStatus;
  type: ShyChannelType;
};
