// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShyComment = {
  comment_id: string;
  topic_id: string;
  content: string;
  channel_id: string;
  author_public_key: string;
  author_sig: string;
  author_proof_ids: string[];
};
