// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyChannel {
  channel_id: string;
  label: string;
  proof_type_ids: string[];
}
