// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyComment } from "./ShyComment";

export type ShyCommentWithProofs = {
  shy_comment: ShyComment;
  img_url: string;
  expression: string;
  public_inputs: string;
  proof: Array<number>;
  proof_public_key: string;
  proof_type_id: string;
};
