// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnterShyChannelAction } from "./EnterShyChannelAction";

export type ShyChannelProofAction = { type: "enter_shy_channel" } & EnterShyChannelAction;
