// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateShyPostAction } from "./CreateShyPostAction";
import type { CreateShyPostReplyAction } from "./CreateShyPostReplyAction";

export type ShyPostProofAction =
  | ({ type: "create_shy_post" } & CreateShyPostAction)
  | ({ type: "create_shy_post_reply" } & CreateShyPostReplyAction);
