// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyPost {
  post_id: string;
  topic_id: string;
  content: string;
  channel_id: string;
  shy_topic_proof_id: string;
  author_public_key: string;
  author_sig: string;
}
