// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyPost } from "./ShyPost";

export interface ShyPostSyn1 {
  shy_post: ShyPost;
  proof_identity_input: string;
}
