// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShyProofWithProofType = {
  shy_proof_id: string;
  proof: Array<number>;
  public_inputs: string;
  public_key: string;
  serial_no: string;
  proof_identity_input: string;
  proof_type_id: string;
  proof_idx: number;
  img_url: string;
  expression: string;
};
