// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyPost } from "./ShyPost";

export type ShyPostSyn1 = {
  shy_post: ShyPost;
  img_url: string;
  expression: string;
  public_inputs: string;
  proof: Array<number>;
  proof_public_key: string;
};
