// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyPost {
  title: string;
  post_id: string;
  content: string;
  channel_id: string;
}
