// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateShyPostAction } from "./CreateShyPostAction";

export type ShyPostProofAction = { type: "create_shy_post" } & CreateShyPostAction;
