// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyTopic {
  title: string;
  topic_id: string;
  channel_id: string;
  num_replies: number;
  author_public_key: string;
}
