// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyTopicSyn1 {
  title: string;
  topic_id: string;
  channel_id: string;
  num_replies: number;
  author_public_key: string;
  shy_topic_proof_id: string;
  proof_identity_input: string;
  author_sig: string;
}
