// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyTopicProof {
  shy_topic_proof_id: string;
  proof: Array<number>;
  public_inputs: string;
  public_key: string;
  serial_no: string;
  proof_identity_input: string;
}
