// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShyTopic = {
  title: string;
  topic_id: string;
  channel_id: string;
  total_reply_count: number;
  content: string;
  shy_proof_id: string;
  author_public_key: string;
  author_sig: string;
  sub_channel_id: string;
  total_like_count: bigint;
  author_proof_identity_inputs: string[];
  participant_identity_inputs: string[];
  other_proof_ids: string[];
};
