// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyTopic } from "./ShyTopic";

export interface ShyTopicSyn1 {
  shy_topic: ShyTopic;
  proof_identity_input: string;
}
