// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyProofSyn1 } from "./ShyProofSyn1";
import type { ShyTopic } from "./ShyTopic";

export type ShyTopicSyn1 = { shy_topic: DateTimed<ShyTopic>; shy_proofs: Array<ShyProofSyn1> };
