// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShyTopic {
  title: string;
  topic_id: string;
  channel_id: string;
  num_replies: number;
  content: string;
  shy_topic_proof_id: string;
  author_public_key: string;
  author_sig: string;
  participant_identity_inputs: string[];
}
