// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimed } from "./DateTimed";
import type { ShyProofWithProofType } from "./ShyProofWithProofType";
import type { ShyTopic } from "./ShyTopic";

export type ShyTopicWithProofs = {
  shy_topic: DateTimed<ShyTopic>;
  shy_proofs: Array<ShyProofWithProofType>;
};
