// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyAccount } from "./ShyAccount";

export interface SignInShyAccountResponse {
  shy_account: ShyAccount;
}
