// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpartanCircomDriverProperties = {
  version: string;
  wtns_gen_url: string;
  circuit_url: string;
};
