export interface Envs {
  NEXT_PUBLIC_IS_TEASER: string;
  NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT: string;
  NEXT_PUBLIC_WEBAPP_VACADE_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT: string;
  NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT: string;
}

export const envs: Envs = {
  NEXT_PUBLIC_IS_TEASER: process.env.NEXT_PUBLIC_IS_TEASER,
  NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_CONSOLE_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_PROOF_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_POLL_ENDPOINT,
  NEXT_PUBLIC_WEBAPP_VACADE_ENDPOINT: process.env.NEXT_PUBLIC_WEBAPP_VACADE_ENDPOINT,
  NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_API_SERVER_ENDPOINT,
  NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_ASSET_SERVER_ENDPOINT,
  NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT: process.env.NEXT_PUBLIC_PRFS_SDK_WEB_ENDPOINT,
};
