export const paths = {
  __: "/",
  create: "/create",
  auth: "/auth",
  attestations: "/attestations",
  attestations__create: "/attestations/create",
  attestations__twitter: "/attestations/twitter",
  proofs: "/proofs",
  updates: "/updates",
  privacy: "/privacy",
  id: "/id",
  id__create: "/id/create",
  id__signin: "/id/signin",
  accounts: "/accounts",
};
