// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AttestTwitterAccResponse {
  is_valid: boolean;
  acc_atst_id: string;
}
