// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TwitterAccValidation } from "./TwitterAccValidation";

export interface AttestTwitterAccRequest {
  acc_atst_id: string;
  validation: TwitterAccValidation;
}
