// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitInputTypeProperty } from "./CircuitInputTypeProperty";

export interface CircuitInputType {
  circuit_input_type: string;
  properties_meta: Array<CircuitInputTypeProperty>;
}
