// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CircuitType {
  circuit_type: string;
  desc: string;
  created_at: number;
  driver_inputs_meta: Record<string, any>[];
}
