// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CircuitType {
  circuit_type: string;
  desc: string;
  author: string;
  created_at: number;
  circuit_inputs_meta: Record<string, any>[];
  prioritized_input_type_names: Array<string>;
}
