// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitInputType } from "./CircuitInputType";

export interface CircuitInputMeta {
  type: CircuitInputType;
  label: string;
  desc: string;
  public: boolean;
}
