// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CircuitInputType =
  | "HASH_DATA_1"
  | "MERKLE_PROOF_1"
  | "SIG_DATA_1"
  | "PASSCODE"
  | "PASSCODE_CONFIRM"
  | "MERKLE_SIG_POS_RANGE_V1";
