// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CircuitDriverInstance {
  driver_id: string;
  version: string;
  properties: Record<string, any>;
  created_at: number;
}
