// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CircuitInputMeta {
  name: string;
  label: string;
  type: string;
  desc: string;
  show_priority: number;
  ref: string;
}
