// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CircuitDriver {
  driver_id: string;
  driver_repository_url: string;
  version: string;
  author: string;
  desc: string;
  properties_meta: Record<string, string>;
  created_at: number;
  proof_functions: Record<string, any>[];
}
