// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitInputType } from "./CircuitInputType";

export interface CircuitInput {
  name: string;
  label: string;
  type: CircuitInputType;
  desc: string;
  value: string;
  units: number;
  element_type: string | null;
  ref_type: string | null;
  ref_value: string | null;
}
