// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoCurrencyRates } from "./CryptoCurrencyRates";

export interface CoinbaseExchangeRatesResult {
  currency: string;
  rates: CryptoCurrencyRates;
}
