// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoinbaseExchangeRatesResult } from "./CoinbaseExchangeRatesResult";

export interface ComputeCryptoSizeTotalValuesResponse {
  exchange_rates: CoinbaseExchangeRatesResult;
}
