// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoinbaseExchangeRates } from "./CoinbaseExchangeRates";

export type ComputeCryptoAssetTotalValuesResponse = {
  exchange_rates: CoinbaseExchangeRates;
  updated_row_count: bigint;
};
