// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateCryptoSizeAtstRequest {
  atst_id: string;
  atst_type: string;
  wallet_addr: string;
  cm: string;
  amount: bigint;
  unit: string;
}
