// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroupId } from "./PrfsAtstGroupId";

export type CreatePrfsAttestationRequest = {
  atst_id: string;
  atst_group_id: PrfsAtstGroupId;
  label: string;
  serial_no: string;
  cm: string;
  cm_msg: Array<number>;
  sig: string;
};
