// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSetIns1 } from "./PrfsSetIns1";

export interface CreatePrfsSetRequest {
  prfs_set_ins1: PrfsSetIns1;
}
