// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreatePrfsProofInstanceResponse {
  proof_instance_id: string;
  prfs_ack_sig: string;
}
