// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreatePrfsTreeByPrfsSetRequest {
  set_id: string;
  tree_label: string;
  tree_id: string;
  account_id: string;
}
