// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitInput } from "./CircuitInput";

export interface CreatePrfsProofTypeRequest {
  proof_type_id: string;
  author: string;
  label: string;
  desc: string;
  circuit_id: string;
  circuit_type_id: string;
  circuit_driver_id: string;
  expression: string;
  img_url: string | null;
  img_caption: string | null;
  circuit_inputs: Array<CircuitInput>;
  driver_properties: Record<string, string>;
}
