// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type CreateGroupMemberAtstRequest = {
  atst_id: string;
  atst_type_id: PrfsAtstTypeId;
  atst_group_id: string;
  label: string;
  serial_no: string;
  cm: string;
  member_code: string;
};
