// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePrfsProofTypeRequest = {
  proof_type_id: string;
  author: string;
  label: string;
  desc: string;
  circuit_id: string;
  circuit_type_id: "simple_hash_v1" | "addr_membership_v1" | "merkle_sig_pos_range_v1";
  circuit_type_data: Record<string, any>;
  expression: string;
  img_url: string | null;
  img_caption: string | null;
  driver_properties: { [key: string]: string };
  experimental: boolean;
};
