// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreatePrfsProofInstanceRequest {
  proof_instance_id: "<Uuid>" | string;
  sig: string;
  proof_type_id: "<Uuid>" | string;
  proof: Array<number>;
  public_inputs: Record<string, any>;
}
