// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type CreateCryptoAssetSizeAtstRequest = {
  atst_id: string;
  atst_type_id: PrfsAtstTypeId;
  label: string;
  serial_no: string;
  cm: string;
  cm_msg: Array<number>;
  sig: string;
};
