// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DatedPrfsIndex {
  key: string | null;
  value: string | null;
  serial_no: string | null;
  updated_at: string | null;
  key2: string;
}
