// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSet } from "./PrfsSet";

export interface DynamicSetJson {
  prfs_set: PrfsSet;
  elements_path: string;
}
