// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAsset } from "./CryptoAsset";

export interface FetchCryptoAssetResponse {
  crypto_asset: CryptoAsset;
}
