// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAsset } from "./CryptoAsset";

export interface FetchCryptoAssetResult {
  wallet_addr: string;
  crypto_assets: Array<CryptoAsset>;
}
