// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCryptoAssetSizeAtst } from "./PrfsCryptoAssetSizeAtst";

export interface GetCryptoAssetSizeAtstResponse {
  prfs_crypto_asset_size_atst: PrfsCryptoAssetSizeAtst;
}
