// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetCircuitsRequest {
  page: number;
  circuit_id: "<Uuid>" | string | null;
}
