// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAttestation } from "./PrfsAttestation";

export type GetCryptoAssetSizeAtstResponse = { prfs_attestation: PrfsAttestation };
