// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetCircuitTypesRequest {
  page: number;
  circuit_type: string | null;
}
