// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCryptoSizeAtst } from "./PrfsCryptoSizeAtst";

export interface GetCryptoSizeAtstsResponse {
  rows: Array<PrfsCryptoSizeAtst>;
  next_offset: number | null;
}
