// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCryptoAssetSizeAtst } from "./PrfsCryptoAssetSizeAtst";

export interface GetCryptoAssetSizeAtstsResponse {
  rows: Array<PrfsCryptoAssetSizeAtst>;
  next_offset: number | null;
}
