// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsTree } from "./PrfsTree";

export interface GetLatestPrfsTreeBySetIdResponse {
  prfs_tree: PrfsTree | null;
}
