// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsPollResponse } from "./PrfsPollResponse";

export interface GetPrfsPollResultByPollIdResponse {
  prfs_poll_responses: Array<PrfsPollResponse>;
}
