// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofTypeSyn1 } from "./PrfsProofTypeSyn1";

export type GetPrfsProofTypeByProofTypeIdResponse = { prfs_proof_type: PrfsProofTypeSyn1 };
