// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSetElement } from "./PrfsSetElement";

export type GetPrfsSetElementResponse = { prfs_set_element: PrfsSetElement };
