// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofInstanceSyn1 } from "./PrfsProofInstanceSyn1";

export interface GetPrfsProofInstancesResponse {
  page_idx: number;
  table_row_count: number;
  prfs_proof_instances_syn1: Array<PrfsProofInstanceSyn1>;
}
