// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCircuitSyn1 } from "./PrfsCircuitSyn1";

export interface GetPrfsCircuitByCircuitIdResponse {
  prfs_circuit_syn1: PrfsCircuitSyn1;
}
