// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCircuitType } from "./PrfsCircuitType";

export interface GetPrfsCircuitTypeByCircuitTypeIdResponse {
  prfs_circuit_type: PrfsCircuitType;
}
