// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSet } from "./PrfsSet";

export interface GetPrfsSetsResponse {
  page_idx: number;
  page_size: number;
  prfs_sets: Array<PrfsSet>;
}
