// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsPoll } from "./PrfsPoll";

export interface GetPrfsPollByPollIdResponse {
  prfs_poll: PrfsPoll;
}
