// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofSyn1 } from "./PrfsProofSyn1";

export type GetPrfsProofByProofIdResponse = { prfs_proof: PrfsProofSyn1 };
