// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofType } from "./PrfsProofType";

export interface GetPrfsProofTypesResponse {
  next_offset: number | null;
  prfs_proof_types: Array<PrfsProofType>;
}
