// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetPrfsTreeLeafNodesRequest {
  page_idx: number;
  page_size: number;
  set_id: "<Uuid>" | string;
}
