// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsTreeNode } from "./PrfsTreeNode";

export interface GetPrfsTreeNodesResponse {
  prfs_tree_nodes: Array<PrfsTreeNode>;
}
