// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodePos } from "./NodePos";

export interface GetPrfsTreeNodesByPosRequest {
  tree_id: string;
  pos: Array<NodePos>;
}
