// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsIdApp } from "./PrfsIdApp";

export interface GetPrfsIdAppResponse {
  prfs_id_app: PrfsIdApp;
}
