// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofRecord } from "./PrfsProofRecord";

export interface GetPrfsProofRecordResponse {
  proof_record: PrfsProofRecord;
}
