// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetPrfsTreeLeafIndicesRequest {
  set_id: "<Uuid>" | string;
  leaf_vals: Array<string>;
}
