// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroup } from "./PrfsAtstGroup";

export type GetPrfsAtstGroupsResponse = { rows: Array<PrfsAtstGroup>; next_offset: number | null };
