// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroup } from "./PrfsAtstGroup";

export type GetPrfsAtstGroupByGroupIdResponse = { atst_group: PrfsAtstGroup };
