// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroupType } from "./PrfsAtstGroupType";

export type GetPrfsAtstGroupsByGroupTypeRequest = { offset: number; group_type: PrfsAtstGroupType };
