// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetPrfsProofTypesRequest {
  page: number;
  proof_type_id: "<Uuid>" | string;
}
