// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofInstanceSyn1 } from "./PrfsProofInstanceSyn1";

export interface GetPrfsProofInstanceByInstanceIdResponse {
  prfs_proof_instance_syn1: PrfsProofInstanceSyn1;
}
