// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsProofInstance } from "./PrfsProofInstance";

export interface GetPrfsProofInstanceByShortIdResponse {
  prfs_proof_instance: PrfsProofInstance;
}
