// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetPrfsAssetMetaResponse {
  driver_id: string;
  asset_urls: Array<string>;
}
