// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsCircuitDriver } from "./PrfsCircuitDriver";

export interface GetPrfsCircuitDriverByDriverIdResponse {
  prfs_circuit_driver: PrfsCircuitDriver;
}
