// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyPost } from "./ShyPost";

export interface GetShyPostsResponse {
  next_idx: number;
  social_posts: Array<ShyPost>;
}
