// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyChannel } from "./ShyChannel";

export interface GetShyChannelsResponse {
  shy_channels: Array<ShyChannel>;
  next_offset: number | null;
}
