// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShyPost } from "./ShyPost";

export interface GetShyPostsResponse {
  shy_posts: Array<ShyPost>;
  next_offset: number | null;
}
