// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocialPost } from "./SocialPost";

export interface GetSocialPostsResponse {
  next_idx: number;
  social_posts: Array<SocialPost>;
}
