// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ImportPrfsAttestationsToPrfsSetResponse {
  set_id: string;
  rows_affected: bigint;
}
