// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroupId } from "./PrfsAtstGroupId";

export type ImportPrfsAttestationsToPrfsSetRequest = {
  atst_group_id: PrfsAtstGroupId;
  prfs_set_id: string;
};
