// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ImportPrfsSetElementsRequest {
  destination_type: string;
  destination_id: string;
  set_id: string;
}
