// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstType } from "./PrfsAtstType";

export interface ImportPrfsAttestationsToPrfsSetRequest {
  topic: PrfsAtstType;
  dest_set_id: string;
}
