// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAccAtst } from "./PrfsAccAtst";

export interface InsertPrfsAccAtstRequest {
  prfs_acc_atst: PrfsAccAtst;
}
