// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OpenPrfsIdSessionMsgPayload {
  key: string;
  value: Array<number> | null;
  ticket: string;
}
