// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollQuestionType } from "./PollQuestionType";

export interface PollQuestion {
  label: string;
  type: PollQuestionType;
  required: boolean;
  choices: Record<string, any>[];
}
