// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsPollResponse = {
  poll_id: string;
  proof_instance_id: string;
  serial_no: string;
  value: string[];
};
