// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestTwitterAccRequest } from "./AttestTwitterAccRequest";
import type { ComputeCryptoAssetSizeTotalValuesRequest } from "./ComputeCryptoAssetSizeTotalValuesRequest";
import type { CreateCryptoAssetSizeAtstRequest } from "./CreateCryptoAssetSizeAtstRequest";
import type { FetchCryptoAssetRequest } from "./FetchCryptoAssetRequest";
import type { GetCryptoAssetSizeAtstRequest } from "./GetCryptoAssetSizeAtstRequest";
import type { GetCryptoAssetSizeAtstsRequest } from "./GetCryptoAssetSizeAtstsRequest";
import type { GetTwitterAccAtstRequest } from "./GetTwitterAccAtstRequest";
import type { GetTwitterAccAtstsRequest } from "./GetTwitterAccAtstsRequest";
import type { ValidateTwitterAccRequest } from "./ValidateTwitterAccRequest";

export type PrfsAtstApiRequest =
  | ({ type: "fetch_crypto_asset" } & FetchCryptoAssetRequest)
  | ({ type: "create_crypto_asset_size_atst" } & CreateCryptoAssetSizeAtstRequest)
  | ({ type: "get_crypto_asset_size_atst" } & GetCryptoAssetSizeAtstRequest)
  | ({ type: "get_crypto_asset_size_atsts" } & GetCryptoAssetSizeAtstsRequest)
  | ({ type: "compute_crypto_asset_size_total_values" } & ComputeCryptoAssetSizeTotalValuesRequest)
  | ({ type: "validate_twitter_acc" } & ValidateTwitterAccRequest)
  | ({ type: "attest_twitter_acc" } & AttestTwitterAccRequest)
  | ({ type: "get_twitter_acc_atsts" } & GetTwitterAccAtstsRequest)
  | ({ type: "get_twitter_acc_atst" } & GetTwitterAccAtstRequest);
