// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsSet {
  set_id: string;
  label: string;
  author: string;
  desc: string;
  hash_algorithm: string;
  cardinality: bigint;
  element_type: string;
  topic: string;
  created_at: string;
}
