// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSetElementDataType } from "./PrfsSetElementDataType";

export interface PrfsSetElementData {
  label: string;
  type: PrfsSetElementDataType;
  val: string;
}
