// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestProofGenPayload } from "./RequestProofGenPayload";
import type { RequestSignInPayload } from "./RequestSignInPayload";

export type PrfsIdSessionMsg =
  | { RequestSignIn: RequestSignInPayload }
  | { RequestProofGen: RequestProofGenPayload };
