// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestTwitterAccRequest } from "./AttestTwitterAccRequest";
import type { ComputeCryptoAssetTotalValuesRequest } from "./ComputeCryptoAssetTotalValuesRequest";
import type { CreatePrfsAttestationRequest } from "./CreatePrfsAttestationRequest";
import type { FetchCryptoAssetRequest } from "./FetchCryptoAssetRequest";
import type { GetPrfsAttestationRequest } from "./GetPrfsAttestationRequest";
import type { GetPrfsAttestationsRequest } from "./GetPrfsAttestationsRequest";
import type { GetTwitterAccAtstRequest } from "./GetTwitterAccAtstRequest";
import type { GetTwitterAccAtstsRequest } from "./GetTwitterAccAtstsRequest";
import type { ValidateTwitterAccRequest } from "./ValidateTwitterAccRequest";

export type PrfsAtstApiRequest =
  | ({ type: "fetch_crypto_asset" } & FetchCryptoAssetRequest)
  | ({ type: "compute_crypto_asset_total_values" } & ComputeCryptoAssetTotalValuesRequest)
  | ({ type: "create_crypto_asset_atst" } & CreatePrfsAttestationRequest)
  | ({ type: "create_prfs_attestation" } & CreatePrfsAttestationRequest)
  | ({ type: "get_prfs_attestations" } & GetPrfsAttestationsRequest)
  | ({ type: "get_prfs_attestation" } & GetPrfsAttestationRequest)
  | ({ type: "validate_twitter_acc" } & ValidateTwitterAccRequest)
  | ({ type: "attest_twitter_acc" } & AttestTwitterAccRequest)
  | ({ type: "get_twitter_acc_atsts" } & GetTwitterAccAtstsRequest)
  | ({ type: "get_twitter_acc_atst" } & GetTwitterAccAtstRequest);
