// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddPrfsIndexRequest } from "./AddPrfsIndexRequest";
import type { CreatePrfsDynamicSetElementRequest } from "./CreatePrfsDynamicSetElementRequest";
import type { CreatePrfsPollRequest } from "./CreatePrfsPollRequest";
import type { CreatePrfsProofInstanceRequest } from "./CreatePrfsProofInstanceRequest";
import type { CreatePrfsProofTypeRequest } from "./CreatePrfsProofTypeRequest";
import type { CreatePrfsSetRequest } from "./CreatePrfsSetRequest";
import type { CreateTreeOfPrfsSetRequest } from "./CreateTreeOfPrfsSetRequest";
import type { GetLeastRecentPrfsIndexRequest } from "./GetLeastRecentPrfsIndexRequest";
import type { GetPrfsCircuitByCircuitIdRequest } from "./GetPrfsCircuitByCircuitIdRequest";
import type { GetPrfsCircuitDriverByDriverIdRequest } from "./GetPrfsCircuitDriverByDriverIdRequest";
import type { GetPrfsCircuitDriversRequest } from "./GetPrfsCircuitDriversRequest";
import type { GetPrfsCircuitTypeByCircuitTypeIdRequest } from "./GetPrfsCircuitTypeByCircuitTypeIdRequest";
import type { GetPrfsCircuitTypesRequest } from "./GetPrfsCircuitTypesRequest";
import type { GetPrfsCircuitsRequest } from "./GetPrfsCircuitsRequest";
import type { GetPrfsIndicesRequest } from "./GetPrfsIndicesRequest";
import type { GetPrfsPollByPollIdRequest } from "./GetPrfsPollByPollIdRequest";
import type { GetPrfsPollsRequest } from "./GetPrfsPollsRequest";
import type { GetPrfsProofInstanceByInstanceIdRequest } from "./GetPrfsProofInstanceByInstanceIdRequest";
import type { GetPrfsProofInstanceByShortIdRequest } from "./GetPrfsProofInstanceByShortIdRequest";
import type { GetPrfsProofInstancesRequest } from "./GetPrfsProofInstancesRequest";
import type { GetPrfsProofTypeByProofTypeIdRequest } from "./GetPrfsProofTypeByProofTypeIdRequest";
import type { GetPrfsProofTypesRequest } from "./GetPrfsProofTypesRequest";
import type { GetPrfsSetBySetIdRequest } from "./GetPrfsSetBySetIdRequest";
import type { GetPrfsSetElementsRequest } from "./GetPrfsSetElementsRequest";
import type { GetPrfsSetsBySetTypeRequest } from "./GetPrfsSetsBySetTypeRequest";
import type { GetPrfsSetsRequest } from "./GetPrfsSetsRequest";
import type { GetPrfsTreeLeafIndicesRequest } from "./GetPrfsTreeLeafIndicesRequest";
import type { GetPrfsTreeLeafNodesBySetIdRequest } from "./GetPrfsTreeLeafNodesBySetIdRequest";
import type { GetPrfsTreeNodesByPosRequest } from "./GetPrfsTreeNodesByPosRequest";
import type { ImportPrfsSetElementsRequest } from "./ImportPrfsSetElementsRequest";
import type { PrfsIdentitySignUpRequest } from "./PrfsIdentitySignUpRequest";
import type { SubmitPrfsPollResponseRequest } from "./SubmitPrfsPollResponseRequest";
import type { UpdatePrfsTreeNodeRequest } from "./UpdatePrfsTreeNodeRequest";

export type PrfsApiRequest =
  | ({ type: "get_prfs_circuits_request" } & GetPrfsCircuitsRequest)
  | ({ type: "get_prfs_circuit_by_circuit_id_request" } & GetPrfsCircuitByCircuitIdRequest)
  | ({ type: "prfs_identity_sign_up_request" } & PrfsIdentitySignUpRequest)
  | ({ type: "get_prfs_circuit_drivers_request" } & GetPrfsCircuitDriversRequest)
  | ({
      type: "get_prfs_circuit_driver_by_driver_id_request";
    } & GetPrfsCircuitDriverByDriverIdRequest)
  | ({ type: "get_prfs_circuit_types_request" } & GetPrfsCircuitTypesRequest)
  | ({
      type: "get_prfs_circuit_type_by_circuit_type_id_request";
    } & GetPrfsCircuitTypeByCircuitTypeIdRequest)
  | ({ type: "get_least_recent_prfs_index_request" } & GetLeastRecentPrfsIndexRequest)
  | ({ type: "get_prfs_indices_request" } & GetPrfsIndicesRequest)
  | ({ type: "add_prfs_index_request" } & AddPrfsIndexRequest)
  | ({ type: "get_prfs_polls_request" } & GetPrfsPollsRequest)
  | ({ type: "create_prfs_poll_request" } & CreatePrfsPollRequest)
  | ({ type: "get_prfs_poll_by_poll_id_request" } & GetPrfsPollByPollIdRequest)
  | ({ type: "submit_prfs_poll_response_request" } & SubmitPrfsPollResponseRequest)
  | ({ type: "get_prfs_proof_instances_request" } & GetPrfsProofInstancesRequest)
  | ({
      type: "get_prfs_proof_instance_by_instance_id_request";
    } & GetPrfsProofInstanceByInstanceIdRequest)
  | ({ type: "get_prfs_proof_instance_by_short_id_request" } & GetPrfsProofInstanceByShortIdRequest)
  | ({ type: "create_prfs_proof_instance_request" } & CreatePrfsProofInstanceRequest)
  | ({ type: "get_prfs_proof_types_request" } & GetPrfsProofTypesRequest)
  | ({
      type: "get_prfs_proof_type_by_proof_type_id_request";
    } & GetPrfsProofTypeByProofTypeIdRequest)
  | ({ type: "create_prfs_proof_type_request" } & CreatePrfsProofTypeRequest)
  | ({ type: "get_prfs_set_by_set_id_request" } & GetPrfsSetBySetIdRequest)
  | ({ type: "get_prfs_sets_request" } & GetPrfsSetsRequest)
  | ({ type: "get_prfs_sets_by_set_type_request" } & GetPrfsSetsBySetTypeRequest)
  | ({ type: "create_prfs_set_request" } & CreatePrfsSetRequest)
  | ({ type: "create_prfs_dynamic_set_element_request" } & CreatePrfsDynamicSetElementRequest)
  | ({ type: "create_tree_of_prfs_set_request" } & CreateTreeOfPrfsSetRequest)
  | ({ type: "import_prfs_set_elements_request" } & ImportPrfsSetElementsRequest)
  | ({ type: "get_prfs_set_elements_request" } & GetPrfsSetElementsRequest)
  | ({ type: "get_prfs_set_element_request" } & GetPrfsSetElementsRequest)
  | ({ type: "get_prfs_tree_nodes_by_pos_request" } & GetPrfsTreeNodesByPosRequest)
  | ({ type: "get_prfs_tree_leaf_nodes_by_set_id_request" } & GetPrfsTreeLeafNodesBySetIdRequest)
  | ({ type: "get_prfs_tree_leaf_indices_request" } & GetPrfsTreeLeafIndicesRequest)
  | ({ type: "update_prfs_tree_node_request" } & UpdatePrfsTreeNodeRequest);
