// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsProofRecord {
  public_key: string;
  serial_no: string;
  proof_starts_with: Array<number>;
}
