// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloseSessionResult } from "./CloseSessionResult";
import type { OpenSessionResult } from "./OpenSessionResult";
import type { PutSessionValueResult } from "./PutSessionValueResult";

export type PrfsIdSessionResponsePayload =
  | ({ type: "OPEN_SESSION_RESULT" } & OpenSessionResult)
  | ({ type: "CLOSE_SESSION_RESULT" } & CloseSessionResult)
  | ({ type: "PUT_SESSION_VALUE_RESULT" } & PutSessionValueResult);
