// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsProofInstanceSyn1 {
  proof_instance_id: string;
  proof_type_id: string;
  proof: Array<number>;
  short_id: string;
  expression: string;
  img_url: string | null;
  img_caption: string | null;
  circuit_id: string;
  circuit_type_id: string;
  circuit_driver_id: string;
  proof_type_desc: string;
  proof_type_label: string;
  prfs_ack_sig: string;
  public_inputs_meta: Record<string, any>[];
  public_inputs: Record<string, any>;
  created_at: string;
  proof_type_author: string;
  circuit_desc: string;
  circuit_author: string;
}
