// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstStatus } from "./PrfsAtstStatus";
import type { PrfsAtstType } from "./PrfsAtstType";

export interface PrfsAttestation {
  atst_id: string;
  atst_type: PrfsAtstType;
  label: string;
  cm: string;
  meta: Record<string, any>[];
  status: PrfsAtstStatus;
  value: string;
}
