// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPrfsSetElementResponse } from "./GetPrfsSetElementResponse";
import type { GetPrfsSetElementsResponse } from "./GetPrfsSetElementsResponse";
import type { ImportPrfsAttestationsToPrfsSetResponse } from "./ImportPrfsAttestationsToPrfsSetResponse";

export type PrfsTreeApiResponse =
  | ({ type: "import_prfs_attestations_to_prfs_set" } & ImportPrfsAttestationsToPrfsSetResponse)
  | ({ type: "get_prfs_set_elements" } & GetPrfsSetElementsResponse)
  | ({ type: "get_prfs_set_element" } & GetPrfsSetElementResponse);
