// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsProofType { id: number, label: string, author: string, desc: string, circuit_id: string, driver_id: string, circuit_inputs: Record<number, any>, driver_properties: Record<string, any>, created_at: number, }