// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstStatus } from "./PrfsAtstStatus";
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type PrfsAttestation = {
  atst_id: string;
  atst_type_id: PrfsAtstTypeId;
  label: string;
  cm: string;
  meta: Record<string, any>[];
  status: PrfsAtstStatus;
  value: string;
};
