// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsidSessionApiResponseType =
  | { type: "PUT_SESSION_VAL" }
  | { type: "DELETE_SESSION_VAL" };
