// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsAccount = {
  account_id: string;
  public_key: string;
  avatar_color: string;
  policy_ids: string[];
};
