// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsAtstValue = {
  label: string;
  value_raw: string;
  value_int: string;
  meta: string | null;
};
