// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteSessionValueResponse } from "./DeleteSessionValueResponse";
import type { PutSessionValueResponse } from "./PutSessionValueResponse";

export type PrfsIdSessionApiResponse =
  | ({ type: "PUT_SESSION_VAL" } & PutSessionValueResponse)
  | ({ type: "DELETE_SESSION_VAL" } & DeleteSessionValueResponse);
