// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsProofInstanceSyn1 {
  proof_instance_id: string;
  proof_type_id: string;
  proof: Array<number>;
  expression: string;
  img_url: string;
  circuit_id: string;
  driver_id: string;
  proof_desc: string;
  proof_label: string;
  public_inputs: Record<string, any>;
  created_at: string;
}
