// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsProofInstance {
  proof_instance_id: string;
  proof_type_id: string;
  short_id: string;
  proof: Array<number>;
  public_inputs: Record<string, any>;
  created_at: string;
}
