// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsCircuitDriver {
  circuit_driver_id: string;
  label: string;
  driver_repository_url: string;
  version: string;
  author: string;
  desc: string;
  circuit_types: string[];
  driver_properties_meta: Record<string, any>[];
  created_at: string;
}
