// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClosePrfsIdSessionResult } from "./ClosePrfsIdSessionResult";
import type { OpenPrfsIdSessionResult } from "./OpenPrfsIdSessionResult";
import type { PutPrfsIdSessionValueResult } from "./PutPrfsIdSessionValueResult";

export type PrfsIdSessionResponsePayload =
  | ({ type: "open_prfs_id_session_result" } & OpenPrfsIdSessionResult)
  | ({ type: "close_prfs_id_session_result" } & ClosePrfsIdSessionResult)
  | ({ type: "put_prfs_id_session_value_result" } & PutPrfsIdSessionValueResult);
