// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsIdMsgType } from "./PrfsIdMsgType";

export interface PrfsIdMsg<T> {
  type: PrfsIdMsgType;
  error: string | null;
  payload: T | null;
}
