// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type PrfsSet = {
  set_id: string;
  label: string;
  author: string;
  desc: string;
  hash_algorithm: string;
  cardinality: bigint;
  element_type: string;
  atst_type_id: PrfsAtstTypeId;
  created_at: string;
};
