// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClosePrfsIdSessionMsgPayload } from "./ClosePrfsIdSessionMsgPayload";
import type { OpenPrfsIdSessionMsgPayload } from "./OpenPrfsIdSessionMsgPayload";

export type PrfsIdSessionMsg =
  | ({ type: "open_prfs_id_session" } & OpenPrfsIdSessionMsgPayload)
  | ({ type: "close_prfs_id_session" } & ClosePrfsIdSessionMsgPayload);
