// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PrfsTree {
  label: string;
  tree_id: string;
  set_id: string;
  merkle_root: string;
  tree_depth: number;
  finite_field: string;
  elliptic_curve: string;
}
