// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitDriver } from "./CircuitDriver";
import type { PublicInput } from "./PublicInput";

export interface PrfsCircuit {
  circuit_id: string;
  label: string;
  desc: string;
  author: string;
  circuit_dsl: string;
  arithmetization: string;
  proof_algorithm: string;
  elliptic_curve: string;
  finite_field: string;
  public_inputs: Array<PublicInput>;
  driver: CircuitDriver;
  created_at: string;
}
