// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsIdMsg } from "./PrfsIdMsg";
import type { RequestProofGenPayload } from "./RequestProofGenPayload";
import type { RequestSignInPayload } from "./RequestSignInPayload";
import type { RequestVerifyProofPayload } from "./RequestVerifyProofPayload";

export type PrfsIdSessionMsg =
  | ({ type: "REQUEST_SIGN_IN" } & PrfsIdMsg<RequestSignInPayload>)
  | ({ type: "REQUEST_PROOF_GEN" } & PrfsIdMsg<RequestProofGenPayload>)
  | ({ type: "REQUEST_VERIFY_PROOF" } & PrfsIdMsg<RequestVerifyProofPayload>);
