// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPrfsSetElementRequest } from "./GetPrfsSetElementRequest";
import type { GetPrfsSetElementsRequest } from "./GetPrfsSetElementsRequest";
import type { ImportPrfsSetElementsRequest } from "./ImportPrfsSetElementsRequest";

export type PrfsTreeApiRequest =
  | ({ type: "import_prfs_set_elements" } & ImportPrfsSetElementsRequest)
  | ({ type: "get_prfs_set_elements" } & GetPrfsSetElementsRequest)
  | ({ type: "get_prfs_set_element" } & GetPrfsSetElementRequest);
