// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsSetElementData = { commitment: string; value_int: string; value_raw: string };
