// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsProofSyn1 = {
  prfs_proof_id: string;
  proof: Array<number>;
  public_inputs: string;
  public_key: string;
  serial_no: string;
  proof_identity_input: string;
  proof_type_id: string;
  expression: string;
  img_url: string | null;
  img_caption: string | null;
  proof_type_label: string;
};
