// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestTwitterAccRequest } from "./AttestTwitterAccRequest";
import type { ComputeCryptoAssetTotalValuesRequest } from "./ComputeCryptoAssetTotalValuesRequest";
import type { CreateGroupMemberAtstRequest } from "./CreateGroupMemberAtstRequest";
import type { CreatePrfsAttestationRequest } from "./CreatePrfsAttestationRequest";
import type { FetchCryptoAssetRequest } from "./FetchCryptoAssetRequest";
import type { GetPrfsAtstGroupsRequest } from "./GetPrfsAtstGroupsRequest";
import type { GetPrfsAttestationRequest } from "./GetPrfsAttestationRequest";
import type { GetPrfsAttestationsByAtstTypeRequest } from "./GetPrfsAttestationsByAtstTypeRequest";
import type { GetTwitterAccAtstRequest } from "./GetTwitterAccAtstRequest";
import type { GetTwitterAccAtstsRequest } from "./GetTwitterAccAtstsRequest";
import type { ValidateGroupMembershipRequest } from "./ValidateGroupMembershipRequest";
import type { ValidateTwitterAccRequest } from "./ValidateTwitterAccRequest";

export type PrfsAtstApiRequest =
  | ({ type: "fetch_crypto_asset" } & FetchCryptoAssetRequest)
  | ({ type: "compute_crypto_asset_total_values" } & ComputeCryptoAssetTotalValuesRequest)
  | ({ type: "create_crypto_asset_atst" } & CreatePrfsAttestationRequest)
  | ({ type: "create_prfs_attestation" } & CreatePrfsAttestationRequest)
  | ({ type: "get_prfs_attestations_by_atst_type" } & GetPrfsAttestationsByAtstTypeRequest)
  | ({ type: "get_prfs_attestation" } & GetPrfsAttestationRequest)
  | ({ type: "get_prfs_atst_groups" } & GetPrfsAtstGroupsRequest)
  | ({ type: "create_group_member_atst" } & CreateGroupMemberAtstRequest)
  | ({ type: "validate_group_membership" } & ValidateGroupMembershipRequest)
  | ({ type: "validate_twitter_acc" } & ValidateTwitterAccRequest)
  | ({ type: "attest_twitter_acc" } & AttestTwitterAccRequest)
  | ({ type: "get_twitter_acc_atsts" } & GetTwitterAccAtstsRequest)
  | ({ type: "get_twitter_acc_atst" } & GetTwitterAccAtstRequest);
