// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignInPrfsIdentityRequest } from "./SignInPrfsIdentityRequest";
import type { SignUpPrfsIdentityRequest } from "./SignUpPrfsIdentityRequest";

export type PrfsIdApiRequest =
  | ({ type: "sign_in_prfs_identity" } & SignInPrfsIdentityRequest)
  | ({ type: "sign_up_prfs_identity" } & SignUpPrfsIdentityRequest);
