// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatePrfsProofAction } from "./CreatePrfsProofAction";

export type PrfsProofAction = { type: "create_prfs_proof" } & CreatePrfsProofAction;
