// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetPrfsIdSessionValueRequest } from "./GetPrfsIdSessionValueRequest";
import type { PutPrfsIdSessionValueRequest } from "./PutPrfsIdSessionValueRequest";

export type PrfsIdSessionApiRequest =
  | ({ type: "get_prfs_id_session_value" } & GetPrfsIdSessionValueRequest)
  | ({ type: "put_prfs_id_session_value" } & PutPrfsIdSessionValueRequest);
