// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsSetType } from "./PrfsSetType";

export interface PrfsSetIns1 {
  set_id: string;
  set_type: PrfsSetType;
  label: string;
  author: string;
  desc: string;
  hash_algorithm: string;
  cardinality: bigint;
  merkle_root: string;
  tree_depth: number;
  element_type: string;
  finite_field: string;
  elliptic_curve: string;
  topic: string;
}
