// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoAssetMeta } from "./CryptoAssetMeta";
import type { GroupMemberAtstMeta } from "./GroupMemberAtstMeta";

export type PrfsAtstMeta =
  | ({ type: "crypto_asset" } & CryptoAssetMeta)
  | ({ type: "group_member" } & GroupMemberAtstMeta);
