// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type PrfsAtstGroup = {
  atst_group_id: string;
  atst_type_id: PrfsAtstTypeId;
  label: string;
  desc: string;
};
