// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstGroupId } from "./PrfsAtstGroupId";
import type { PrfsAtstGroupType } from "./PrfsAtstGroupType";

export type PrfsAtstGroup = {
  atst_group_id: PrfsAtstGroupId;
  label: string;
  desc: string;
  group_type: PrfsAtstGroupType;
};
