// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrfsIdMsgType =
  | "HANDSHAKE"
  | "SIGN_IN_RESULT"
  | "PROOF_GEN_RESULT"
  | "VERIFY_PROOF_RESULT"
  | "REQUEST_SIGN_IN"
  | "REQUEST_PROOF_GEN"
  | "REQUEST_VERIFY_PROOF"
  | "GET_MSG";
