// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteSessionValueRequest } from "./DeleteSessionValueRequest";
import type { PutSessionValueRequest } from "./PutSessionValueRequest";

export type PrfsIdSessionApiRequest =
  | ({ type: "PUT_SESSION_VAL" } & PutSessionValueRequest)
  | ({ type: "DELETE_SESSION_VAL" } & DeleteSessionValueRequest);
