// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeletePrfsIdSessionValueRequest } from "./DeletePrfsIdSessionValueRequest";
import type { PutPrfsIdSessionValueRequest } from "./PutPrfsIdSessionValueRequest";

export type PrfsIdSessionApiRequest =
  | ({ type: "put_prfs_id_session_value" } & PutPrfsIdSessionValueRequest)
  | ({ type: "delete_prfs_id_session_value" } & DeletePrfsIdSessionValueRequest);
