// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteSessionValueResponse } from "./DeleteSessionValueResponse";
import type { PutSessionValueResponse } from "./PutSessionValueResponse";

export type PrfsIdSessionApiResponse =
  | ({ type: "put_session_val" } & PutSessionValueResponse)
  | ({ type: "delete_session_val" } & DeleteSessionValueResponse);
