// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAccAtstStatus } from "./PrfsAccAtstStatus";

export interface PrfsAccAtst {
  acc_atst_id: string;
  atst_type: string;
  dest: string;
  account_id: string;
  cm: string;
  username: string;
  avatar_url: string;
  document_url: string;
  status: PrfsAccAtstStatus;
}
