// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitType } from "./CircuitType";

export interface PrfsCircuitType {
  circuit_type: CircuitType;
  desc: string;
  author: string;
  created_at: string;
  circuit_inputs_meta: Record<string, any>[];
  public_inputs_meta: Record<string, any>[];
}
