// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CircuitInputType } from "./CircuitInputType";

export interface PublicInputInstanceEntry {
  label: string;
  type: CircuitInputType;
  desc: string;
  value: string;
  ref: string | null;
}
