// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicInputType } from "./PublicInputType";

export interface PublicInputMeta {
  type: PublicInputType;
  label: string;
  desc: string;
}
