// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicInputType } from "./PublicInputType";

export interface PublicInputInstanceEntry {
  label: string;
  type: PublicInputType;
  desc: string;
  value: string;
  ref: string | null;
}
