// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RawCircuitInputMeta { type: string, label: string, desc: string, public: boolean, }