// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RawPrfsTreeNode {
  tree_id: string;
  set_id: string;
  pos_w: number;
  pos_h: number;
  val: Array<number>;
  meta: string | null;
}
