// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsIdentityType } from "./PrfsIdentityType";

export interface SignUpPrfsIdentityRequest {
  identity_id: string;
  public_key: string;
  avatar_color: string;
  identity_type: PrfsIdentityType;
}
