// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsIdentity } from "./PrfsIdentity";

export interface SignInPrfsIdentityResponse {
  prfs_identity: PrfsIdentity;
}
