// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAccount } from "./PrfsAccount";

export type SignInPrfsAccountResponse = { prfs_account: PrfsAccount };
