// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SubmitPrfsPollResponseRequest {
  poll_id: string;
  serial_no: string;
  value: string[];
  proof_instance_id: string;
  account_id: string | null;
  proof_type_id: string;
  proof: Array<number>;
  public_inputs: Record<string, any>;
}
