// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TwitterAccValidation {
  atst_type: string;
  dest: string;
  account_id: string;
  cm: string;
  username: string;
  avatar_url: string;
  document_url: string;
}
