// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstType } from "./PrfsAtstType";

export interface UpdatePrfsTreeByNewAtstRequest {
  atst_type: PrfsAtstType;
}
