// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrfsAtstTypeId } from "./PrfsAtstTypeId";

export type UpdatePrfsTreeByNewAtstResponse = { atst_type_id: PrfsAtstTypeId };
