// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidateGroupMembershipResponse = {
  is_valid: boolean;
  label: string;
  error: string | null;
};
