// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ValidateTwitterAccRequest {
  tweet_url: string;
  twitter_handle: string;
}
