// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValidateGroupMembershipRequest = { atst_group_id: string; member_code: string };
